# Generated by Django 2.2.3 on 2019-07-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('joining', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Employee')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.membership'),
        ),
    ]
